"""initial_schema

Revision ID: e85e4565cafc
Revises: 
Create Date: 2026-04-27 18:37:55.985485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85e4565cafc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Element Plus图标名'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('majors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='专业名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='工号/账号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'teacher'), nullable=False, comment='角色'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='所属院系'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1启用 0禁用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='Logo URL'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='官网链接'),
    sa.Column('description', sa.String(length=300), nullable=True, comment='简介'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('is_free', sa.SmallInteger(), nullable=False, comment='1免费 0付费'),
    sa.Column('rating', sa.SmallInteger(), nullable=False, comment='评分1-5'),
    sa.Column('is_featured', sa.SmallInteger(), nullable=False, comment='是否精选'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ai_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='Markdown内容'),
    sa.Column('cover_url', sa.String(length=500), nullable=True, comment='封面图'),
    sa.Column('category', sa.Enum('contest', 'notice', 'honor', 'other'), nullable=False, comment='分类：contest赛事报道 notice活动通知 honor荣誉展示 other其他'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='作者ID'),
    sa.Column('status', sa.Enum('draft', 'published'), nullable=False, comment='状态'),
    sa.Column('is_top', sa.SmallInteger(), nullable=False, comment='是否置顶'),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='操作对象类型'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='操作对象ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='详情'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='作品名称'),
    sa.Column('author_names', sa.String(length=200), nullable=False, comment='参赛学生姓名，逗号分隔'),
    sa.Column('guide_teacher', sa.String(length=100), nullable=True, comment='指导教师'),
    sa.Column('major_id', sa.Integer(), nullable=True, comment='专业ID'),
    sa.Column('academic_year', sa.String(length=20), nullable=False, comment='学年，如2024-2025'),
    sa.Column('semester', sa.SmallInteger(), nullable=False, comment='1上学期 2下学期'),
    sa.Column('contest_name', sa.String(length=200), nullable=True, comment='赛事名称'),
    sa.Column('award', sa.String(length=50), nullable=True, comment='获奖情况'),
    sa.Column('cover_url', sa.String(length=500), nullable=True, comment='封面图'),
    sa.Column('content', sa.Text(), nullable=True, comment='Markdown内容'),
    sa.Column('demo_url', sa.String(length=500), nullable=True, comment='演示链接'),
    sa.Column('attachment_url', sa.String(length=500), nullable=True, comment='附件链接'),
    sa.Column('status', sa.Enum('draft', 'published', 'archived'), nullable=False, comment='状态'),
    sa.Column('publisher_id', sa.Integer(), nullable=True, comment='发布者ID'),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('operation_logs')
    op.drop_table('news')
    op.drop_table('ai_tools')
    op.drop_table('users')
    op.drop_table('majors')
    op.drop_table('ai_categories')
    # ### end Alembic commands ###
